// let age = 80


// if (age <=17) {
//     console.log("underage");
    
// }

// else if (condition) {
    
// } ( age >=18 && age <=65) {
//     console.log("insurable");
    
// }else { console.log("out of range");}


// let num = 2

// if (num % 5 === 0 && num % 3 === 0) { console.log("fizz buzz");

// else if (num % 5 === 0) console.log("buzz");

// else if (num % 3 === 0) console.log("fizz");

// else {console.log("mate dont be stupid");}
    
// } 

// for (let i = 5; i > 0; i--) {

// console.log("loop" + i);
// if (i ===3)break
// }

let names = ['john','mary','bob','joe']

for (i of names){
console.log(i);

}
